global:
  g2pPbmsBgTaskHostname: g2p-pbms-bg-task.dev.openg2p.org

  keycloakBaseUrl: https://keycloak.openg2p.org
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  g2pPbmsBgTaskClientId: 'openg2p-pbms-bg-task-{{ .Release.Namespace }}'
  g2pPbmsBgTaskClientSecret: ''

  keymanagerAuthEnabled: false
  keymanagerG2pPbmsBgTaskAppId: OPENG2P_G2P_PBMS_BG_TASK
  pbmsInstallationName: 'pbms'
  registryInstallationName: 'social-registry'

openg2p-pbms-bg-task-api:
  enabled: true
  nameOverride: api

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

openg2p-pbms-bg-task-celery-beat-producers:
  enabled: true
  nameOverride: celery-beat-producer    

openg2p-pbms-bg-task-celery-workers:
  enabled: true
  nameOverride: celery-worker

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

postgresql:
  enabled: true
  auth:
    username: bgtaskuser
    database: bgtaskdb
  additionalDbs:
    enabled: true
    userPasswordsExistingSecret: ""
    userPasswords:
      keymgruser: ""
  primary:
    resourcesPreset: "small"
    extendedConfiguration: |-
      wal_level = logical
      max_wal_senders = 20
      max_replication_slots = 10

redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

artifactory:
  enabled: false
  image:
    repository: mosipid/artifactory-server
    tag: 1.4.1-ES
  resources: {}

softhsm:
  enabled: false
  # Hardcoding this for now. else every upgrade will reset the pin
  securityPIN: MTg5MTAwMTc=
  resources: {}

keymanager:
  enabled: true
  hostname: '{{ tpl .Values.global.g2pPbmsBgTaskHostname $ }}'
  authEnabled: '{{ .Values.global.keymanagerAuthEnabled }}'
  istio:
    enabled: true
  keystoreType: PKCS12
  springConfig:
    names: application,kernel
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""
  envVars:
    auth_server_admin_allowed_audience: 'openg2p-pbms-bg-task,openg2p-pbms-bg-task-{{ .Release.Namespace }}'
  envVarsFrom:
    db_dbuser_password:
      secretKeyRef:
        name: '{{ .Release.Name }}-postgresql-addl-user-passwords'
        key: keymgruser
  postgresInit:
    envVarsFrom:
      DBUSER_PWD:
        secretKeyRef:
          name: '{{ .Release.Name }}-postgresql-addl-user-passwords'
          key: keymgruser
  keygen:
    appIdsList:
      - '{{ tpl .Values.global.keymanagerG2pPbmsBgTaskAppId $ }}'
    baseKeysList:
      - '{{ tpl .Values.global.keymanagerG2pPbmsBgTaskAppId $ }}:ENCRYPT'
  persistence:
    enabled: true