apiVersion: v2
name: openg2p-pbms
description: A Helm chart for OpenG2P PBMS
type: application
version: 2.0.0
dependencies:
- name: odoo
  version: 26.2.9
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: odoo.enabled
- name: minio
  version: 12.12.2
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: minio.enabled
- name: keymanager
  version: 12.0.1
  repository: https://openg2p.github.io/openg2p-helm
  condition: keymanager.enabled
icon: https://openg2p.github.io/openg2p-helm/openg2p-logo.png
annotations:
  catalog.cattle.io/display-name: "OpenG2P PBMS"
  openg2p.org/add-to-rancher: ""