global:
  keycloakBaseUrl: https://keycloak.openg2p.sandbox.net
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  postgresqlHost: openg2p-commons-postgresql
  opensearchInstallationName: openg2p-commons-opensearch
  reportingInstallationName: openg2p-commons-reporting

  mailInstallationName: openg2p-commons-mail

  sysAdminEmail: admin@openg2p.sandbox.net

  pbmsOdooOidcClientID: 'openg2p-pbms-{{ .Release.Namespace }}'
  pbmsOdooOidcClientSecret: ''

  minioInstallationName: openg2p-commons-minio

  g2pPbmsBgTaskHostname: g2p-pbms-bg-task.dev.openg2p.org

  keycloakBaseUrl: https://keycloak.openg2p.org
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  g2pPbmsBgTaskClientId: 'openg2p-pbms-bg-task-{{ .Release.Namespace }}'
  g2pPbmsBgTaskClientSecret: ''

  keymanagerBaseUrl: https://keymanager.openg2p.org
  keymanagerAuthEnabled: 'false'
  keymanagerInstallationName: openg2p-commons-keymanager
  keymanagerG2pPbmsBgTaskAppId: OPENG2P_G2P_PBMS_BG_TASK

  pbmsInstallationName: 'pbms'
  registryInstallationName: 'registry'

# TODO: change
hostname: admin-pbms.devops.openg2p.org

postgres-init:
  enabled: true
  postgresql:
    host: '{{ .Values.global.postgresqlHost }}'
    port: 5432
    # Hard coding. Same as one defined under Odoo
    existingSecret: openg2p-commons-postgresql
    existingSecretPostgresPasswordKey: postgres-password
  databases:
    # Same as db in Odoo - make sure any changes to the name are synced with Odoo definitions
    - name: '{{ .Release.Name }}_db'
      user: '{{ .Release.Name}}_db_user'
      # Same as odoo.externalDatabase.existingSecret - make sure these two are same if any changes are made.
      secret: '{{ .Release.Name }}'
      # As convention same as user
      secretUserPasswordKey: '{{ .Release.Name}}_db_user'
    - name: '{{ .Release.Name }}_bgtask_db'
      user: '{{ .Release.Name}}_bgtask_db_user'
      secret: '{{ .Release.Name }}_bgtask'
      secretUserPasswordKey: '{{ .Release.Name}}_bgtask_db_user'

odoo:
  enabled: true

  oidcIssuerUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}'
  oidcClientId: '{{ tpl .Values.global.pbmsOdooOidcClientID $ }}'
  oidcClientSecret: '{{ tpl .Values.global.pbmsOdooOidcClientSecret $ }}'

  extraAddonsUrlsToPull: ''

  image:
    repository: openg2p/openg2p-pbms-core
    tag: "3.0.0"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  # TODO: Remove this and use global.sysAdminEmail
  odooEmail: admin@openg2p.org

  postgresql:
    enabled: false
      #database: pbmsdb
      # CREATE DATABASE bgtaskdb;

  externalDatabase:
    create: true
    # NOTE: For few parameter below the Odoo templates have been overridden to accomodate
    # templating. See templates/_helpers.tpl
    host: '{{ .Values.global.postgresqlHost }}'
    port: 5432
    database: '{{ .Release.Name }}_db'
    user: '{{ .Release.Name }}_db_user'
    # Provided via secrets below
    password: ""
    postgresqlPostgresUser: "postgres"
    # Passed via secrets
    postgresqlPostgresPassword: ""
    # The secrets below should be created before this installation is done.
    # Secret for the DB (not Postgresql server)
    existingSecret: '{{ .Release.Name }}'
    # This is secret for PostgreSQL server. Both have different secrets (unlike original Odoo
    # Chart where the same secret contained keys for both Postgres and the database user
    existingPostgresSecret: openg2p-commons-postgresql
    # Same as user name as convention
    existingSecretPasswordKey: '{{ .Release.Name }}_db_user'
    # Hardcoded as this is not likely to change frequently
    existingSecretPostgresPasswordKey: postgres-password

  livenessProbe:
    enabled: false

  # TODO: Template the following variables from helm values, instead of hardcoding
  extraEnvVars:
  - name: ODOO_SKIP_MODULES_UPDATE
    value: "yes"
  - name: LIMIT_TIME_REAL
    value: "5000"
  - name: LIST_DB
    value: "False"
  - name: SERVER_WIDE_MODULES
    value: web,queue_job
  - name: LOG_HANDLER
    value: '[":INFO"]'
  - name: LOG_DB
    value: "False"
  - name: EXTRA_ADDONS_URLS_TO_PULL
    value: '{{ tpl .Values.extraAddonsUrlsToPull $ }}'
  - name: S3_URL
    value: http://{{ tpl .Values.global.minioInstallationName $ }}:9000
  - name: S3_REGION
    value: other
  - name: S3_ACCESS_KEY_ID
    value: admin

openg2p-pbms-bg-task-api:
  enabled: true
  nameOverride: api

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'
  envVars:
    BG_TASK_API_DB_USERNAME_SR: 'postgres'
    BG_TASK_API_DB_HOSTNAME_SR: '{{ tpl .Values.global.registryInstallationName $ }}-postgresql'
    BG_TASK_API_DB_PORT_SR: 5432
    BG_TASK_API_DB_DBNAME_SR: 'socialregistrydb'

    BG_TASK_API_DB_USERNAME: 'postgres'
    BG_TASK_API_DB_HOSTNAME: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_API_DB_PORT: 5432
    BG_TASK_API_DB_DBNAME: 'bgtaskdb'

openg2p-pbms-bg-task-celery-beat-producers:
  enabled: true
  nameOverride: celery-beat-producer

  envVars:
    BG_TASK_CELERY_BEAT_PRODUCER_FREQUENCY: 10
    BG_TASK_CELERY_BEAT_BATCH_SIZE: 500
    BG_TASK_CELERY_BEAT_NO_OF_TASKS_TO_PROCESS: 2

    # Background Task Database
    BG_TASK_CELERY_BEAT_DB_USERNAME: 'postgres'
    BG_TASK_CELERY_BEAT_DB_HOSTNAME: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_CELERY_BEAT_DB_PORT: 5432
    BG_TASK_CELERY_BEAT_DB_DBNAME: 'bgtaskdb'

    # Social Registry Database
    BG_TASK_CELERY_BEAT_DB_USERNAME_SR: 'postgres'
    BG_TASK_CELERY_BEAT_DB_HOSTNAME_SR: '{{ tpl .Values.global.registryInstallationName $ }}-postgresql'
    BG_TASK_CELERY_BEAT_DB_PORT_SR: 5432
    BG_TASK_CELERY_BEAT_DB_DBNAME_SR: 'socialregistrydb'

    # PBMS Database
    BG_TASK_CELERY_BEAT_DB_USERNAME_PBMS: 'postgres'
    BG_TASK_CELERY_BEAT_DB_HOSTNAME_PBMS: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_CELERY_BEAT_DB_PORT_PBMS: 5432
    BG_TASK_CELERY_BEAT_DB_DBNAME_PBMS: 'pbmsdb'

    BG_TASK_CELERY_BEAT_CELERY_BROKER_URL: redis://{{ tpl .Values.redisInstallationName $ }}:6379/0
    BG_TASK_CELERY_BEAT_CELERY_BACKEND_URL: redis://{{ tpl .Values.redisInstallationName $ }}:6379/0


openg2p-pbms-bg-task-celery-workers:
  enabled: true
  nameOverride: celery-worker

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

  envVars:
    BG_TASK_CELERY_WORKERS_G2P_BRIDGE_BASE_URL: "https://g2pbridge-api"
    BG_TASK_CELERY_WORKERS_CELERY_BROKER_URL: "redis://{{ tpl .Values.redisInstallationName $ }}:6379/0"
    BG_TASK_CELERY_WORKERS_CELERY_BACKEND_URL: "redis://{{ tpl .Values.redisInstallationName $ }}:6379/0"

    BG_TASK_CELERY_WORKERS_BATCH_SIZE: 500

    # BG Task Database
    BG_TASK_CELERY_WORKERS_DB_USERNAME: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_CELERY_WORKERS_DB_PORT: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME: bgtaskdb

    # Social Registry Database
    BG_TASK_CELERY_WORKERS_DB_USERNAME_SR: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME_SR: '{{ tpl .Values.global.registryInstallationName $ }}-postgresql'
    BG_TASK_CELERY_WORKERS_DB_PORT_SR: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME_SR: socialregistrydb

    # PBMS Database
    BG_TASK_CELERY_WORKERS_DB_USERNAME_PBMS: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME_PBMS: '{{ tpl .Values.global.pbmsInstallationName $ }}-postgresql'
    BG_TASK_CELERY_WORKERS_DB_PORT_PBMS: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME_PBMS: pbmsdb

    # Background Task Database (async)
    BG_TASK_CELERY_WORKERS_DB_DRIVER_ASYNC: postgresql+asyncpg
    BG_TASK_CELERY_WORKERS_DB_USERNAME_ASYNC: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME_ASYNC: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_CELERY_WORKERS_DB_PORT_ASYNC: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME_ASYNC: bgtaskdb

    BG_TASK_CELERY_WORKERS_SIGN_KEY_KEYMANAGER_APP_ID: "PBMS"
    BG_TASK_CELERY_WORKERS_SIGN_KEY_KEYMANAGER_REF_ID: ""
    BG_TASK_CELERY_WORKERS_KEYMANAGER_API_TIMEOUT: 10
    BG_TASK_CELERY_WORKERS_KEYMANAGER_API_BASE_URL: '{{ tpl .Values.global.keymanagerBaseUrl $ }}'
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_ENABLED: '{{ tpl .Values.global.keymanagerAuthEnabled $ }}'
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_URL: ""
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_CLIENT_ID: "openg2p-pbms-dev"
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_CLIENT_SECRET: ""

keymanager:
  enabled: false
  hostname: keymanager-pbms.openg2p.sandbox.net
  springConfig:
    names: application,kernel
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""
  envVars:
    auth_server_admin_allowed_audience: 'openg2p-sr,openg2p-sr-{{ .Release.Namespace }},openg2p-pbms,openg2p-pbms-{{ .Release.Namespace }},openg2p-spar-{{ .Release.Namespace }}'
  postgresInit:
    commonAnnotations:
      "helm.sh/hook-weight": "0"
  keygen:
    commonAnnotations:
      "helm.sh/hook-weight": "1"

redis:
  enabled: true
  image:
    registry: docker.io
    repository: openg2p/redis
    tag: 7.2.5-debian-12-r4
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

serviceProviderIngress:
  enabled: false
selfServiceIngress:
  enabled: false

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ include "common.names.fullname" .Subcharts.odoo }}'
    destinationPort: '{{ .Values.odoo.service.port }}'
    prefix: /
    rewriteUri: ""
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""
