global:
  keycloakBaseUrl: https://keycloak.openg2p.sandbox.net
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  sysAdminEmail: admin@openg2p.sandbox.net

  keymanagerBaseUrl: https://keymanager.openg2p.org

  g2pPbmsBgTaskHostname: g2p-pbms-bg-task.dev.openg2p.org

  keycloakBaseUrl: https://keycloak.openg2p.org
  keycloakIssuerUrl: '{{ tpl .Values.global.keycloakBaseUrl $ }}/realms/master'

  g2pPbmsBgTaskClientId: 'openg2p-pbms-bg-task-{{ .Release.Namespace }}'
  g2pPbmsBgTaskClientSecret: ''

  keymanagerAuthEnabled: 'false'
  keymanagerG2pPbmsBgTaskAppId: OPENG2P_G2P_PBMS_BG_TASK
  pbmsInstallationName: 'pbms'
  registryInstallationName: 'social-registry'

# TODO: change
hostname: pbms-gen2.dev.openg2p.org

odoo:
  enabled: true

  oidcIssuerUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}'
  oidcClientId: 'openg2p-pbms-{{ .Release.Namespace }}'
  oidcClientSecret: ''

  extraAddonsUrlsToPull: ''

  image:
    repository: openg2p/openg2p-pbms-core
    tag: "3.0.0"
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  # TODO: Remove this and use global.sysAdminEmail
  odooEmail: admin@openg2p.org

  postgresql:
    enabled: true
    auth:
      username: pbmsuser
      database: pbmsdb
    primary:
      extendedConfiguration: |-
        wal_level = logical
        max_wal_senders = 20
        max_replication_slots = 10
      initdb:
        scripts:
          create-multiple-dbs.sql: |
            CREATE DATABASE bgtaskdb;
    istio:
      enabled: false
      virtualservice:
        enabled: true
        host: "*"
        gateway: ""
        matchPort: 5432
        destination: '{{ include "postgresql.v1.primary.fullname" .Subcharts.odoo.Subcharts.postgresql }}'
        destinationPort: "5432"
      gateway:
        enabled: true
        port: 5432
        host: "*"
        ingressController:
          istio: ingressgateway
        tls:
          enabled: false
          mode: SIMPLE
          credentialName: ""


  livenessProbe:
    enabled: false

  # TODO: Template the following variables from helm values, instead of hardcoding
  extraEnvVars:
  - name: ODOO_SKIP_MODULES_UPDATE
    value: "yes"
  - name: LIMIT_TIME_REAL
    value: "5000"
  - name: LIST_DB
    value: "False"
  - name: SERVER_WIDE_MODULES
    value: web,queue_job
  # not using bitnami smtpHost and smtpPort variables, because they need user and pass as well.
  - name: LOG_HANDLER
    value: '[":INFO"]'
  - name: LOG_DB
    value: "False"
  - name: EXTRA_ADDONS_URLS_TO_PULL
    value: '{{ tpl .Values.extraAddonsUrlsToPull $ }}'

openg2p-pbms-bg-task-api:
  enabled: true
  nameOverride: api

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

openg2p-pbms-bg-task-celery-beat-producers:
  enabled: true
  nameOverride: celery-beat-producer

openg2p-pbms-bg-task-celery-workers:
  enabled: true
  nameOverride: celery-worker

  keymanagerInstallationName: '{{ .Release.Name }}-keymanager'

  envVars:
    BG_TASK_CELERY_WORKERS_G2P_BRIDGE_BASE_URL: "https://g2pbridge-api"
    BG_TASK_CELERY_WORKERS_CELERY_BROKER_URL: "redis://{{ tpl .Values.redisInstallationName $ }}:6379/0"
    BG_TASK_CELERY_WORKERS_CELERY_BACKEND_URL: "redis://{{ tpl .Values.redisInstallationName $ }}:6379/0"

    BG_TASK_CELERY_WORKERS_BATCH_SIZE: 500

    # BG Task Database
    BG_TASK_CELERY_WORKERS_DB_USERNAME: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_CELERY_WORKERS_DB_PORT: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME: bgtaskdb

    # Social Registry Database
    BG_TASK_CELERY_WORKERS_DB_USERNAME_SR: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME_SR: '{{ tpl .Values.global.registryInstallationName $ }}-postgresql'
    BG_TASK_CELERY_WORKERS_DB_PORT_SR: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME_SR: socialregistrydb

    # PBMS Database
    BG_TASK_CELERY_WORKERS_DB_USERNAME_PBMS: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME_PBMS: '{{ tpl .Values.global.pbmsInstallationName $ }}-postgresql'
    BG_TASK_CELERY_WORKERS_DB_PORT_PBMS: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME_PBMS: pbmsdb

    # Background Task Database (async)
    BG_TASK_CELERY_WORKERS_DB_DRIVER_ASYNC: postgresql+asyncpg
    BG_TASK_CELERY_WORKERS_DB_USERNAME_ASYNC: postgres
    BG_TASK_CELERY_WORKERS_DB_HOSTNAME_ASYNC: '{{ tpl .Values.postgresqlInstallationName $ }}'
    BG_TASK_CELERY_WORKERS_DB_PORT_ASYNC: 5432
    BG_TASK_CELERY_WORKERS_DB_DBNAME_ASYNC: bgtaskdb

    BG_TASK_CELERY_WORKERS_SIGN_KEY_KEYMANAGER_APP_ID: "PBMS"
    BG_TASK_CELERY_WORKERS_SIGN_KEY_KEYMANAGER_REF_ID: ""
    BG_TASK_CELERY_WORKERS_KEYMANAGER_API_TIMEOUT: 10
    BG_TASK_CELERY_WORKERS_KEYMANAGER_API_BASE_URL: '{{ tpl .Values.global.keymanagerBaseUrl $ }}'
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_ENABLED: '{{ tpl .Values.global.keymanagerAuthEnabled $ }}'
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_URL: ""
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_CLIENT_ID: "openg2p-pbms-dev"
    BG_TASK_CELERY_WORKERS_KEYMANAGER_AUTH_CLIENT_SECRET: ""

keymanager:
  enabled: false
  hostname: keymanager-pbms.openg2p.sandbox.net
  springConfig:
    names: application,kernel
    profile: default
    gitRepo:
      enabled: true
      repoUrl: https://github.com/openg2p/mosip-config
      branch: master
    rawConfig: ""
  envVars:
    auth_server_admin_allowed_audience: 'openg2p-sr,openg2p-sr-{{ .Release.Namespace }},openg2p-pbms,openg2p-pbms-{{ .Release.Namespace }},openg2p-spar-{{ .Release.Namespace }}'
  postgresInit:
    commonAnnotations:
      "helm.sh/hook-weight": "0"
  keygen:
    commonAnnotations:
      "helm.sh/hook-weight": "1"

redis:
  enabled: true
  image:
    registry: docker.io
    repository: openg2p/redis
    tag: 7.2.5-debian-12-r4
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false

minio:
  enabled: true
  image:
    registry: docker.io
    repository: openg2p/minio
    tag: 2023.12.23-debian-11-r2
  hostname: minio-pbms.openg2p.sandbox.net
  persistence:
    enabled: true
    size: 16Gi

  oidcWellKnownConfigUrl: '{{ tpl .Values.global.keycloakIssuerUrl $ }}/.well-known/openid-configuration'
  oidcClientId: 'openg2p-pbms-minio-{{ .Release.Namespace }}'
  oidcClientSecret: ''

  extraEnvVars:
  - name: MINIO_IDENTITY_OPENID_CONFIG_URL
    value: '{{ tpl .Values.oidcWellKnownConfigUrl $ }}'
  - name: MINIO_IDENTITY_OPENID_CLIENT_ID
    value: '{{ tpl .Values.oidcClientId $ }}'
  - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
    value: '{{ tpl .Values.oidcClientSecret $ }}'
  - name: MINIO_IDENTITY_OPENID_DISPLAY_NAME
    value: Keycloak
  - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
    value: client_roles
  - name: MINIO_IDENTITY_OPENID_SCOPES
    value: openid,profile,email
  - name: MINIO_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC
    value: "on"
  - name: MINIO_IDENTITY_OPENID_CLAIM_USERINFO
    value: "on"

  istio:
    enabled: true
    virtualservice:
      enabled: true
      host: ""
      gateway: "internal"
      destination: '{{ include "common.names.fullname" .Subcharts.minio }}'
      destinationPort: "9001"
    gateway:
      enabled: false
      host: ""
      ingressController:
        istio: ingressgateway
      httpTlsRedirect: true
      httpEnabled: true
      httpsEnabled: false
      tls:
        mode: SIMPLE
        credentialName: ""

serviceProviderIngress:
  enabled: false
selfServiceIngress:
  enabled: false

istio:
  enabled: true
  virtualservice:
    enabled: true
    host: ""
    gateway: "internal"
    destination: '{{ include "common.names.fullname" .Subcharts.odoo }}'
    destinationPort: '{{ .Values.odoo.service.port }}'
    prefix: /
    rewriteUri: ""
  gateway:
    enabled: false
    host: ""
    ingressController:
      istio: ingressgateway
    httpTlsRedirect: true
    httpEnabled: true
    httpsEnabled: false
    tls:
      mode: SIMPLE
      credentialName: ""