global:

  # All the below overriden by same globals in openg2p-pbms/values.yaml
  postgresqlHost: openg2p-commons-postgresql

  registryPostgresqlHost: openg2p-commons-postgresql
  registryDB: 'registry_db'
  registryDBUser: 'registry_db_user'
  registryDBSecret: 'registry'
  registryDBUserPasswordKey: 'registry_db_user'

  pbmsDB: '{{ .Release.Name }}_db'
  pbmsDBUser: '{{ .Release.Name}}_db_user'
  pbmsDBSecret: '{{ .Release.Name }}'
  pbmsDBUserPasswordKey: '{{ .Release.Name}}_db_user'

  pbmsBgTaskDB: '{{ .Release.Name }}_bgtask_db'
  pbmsBgTaskDBUser: '{{ .Release.Name}}_bgtask_db_user'
  pbmsBgTaskDBSecret: '{{ .Release.Name }}_bgtask'
  pbmsBgTaskDBUserPasswordKey: '{{ .Release.Name}}_bgtask_db_user'

  # Default name of Redis that is installed with the parent openg2p-pbms chart
  redisInstallationName: '{{ .Release.Name }}-redis-master'

## Pod extra labels
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}

## Add labels to all the deployed resources
##
commonLabels: {}

## Add annotations to all the deployed resources
##
commonAnnotations: {}

## Annotations for server pods.
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}

replicaCount: 1

## Update strategy - only really applicable for deployments with RWO PVs attached
## If replicas = 1, an update can get "stuck", as the previous pod remains attached to the
## PV, and the "incoming" pod can never start. Changing the strategy to "Recreate" will
## terminate the single previous pod, so that the new, incoming pod can attach to the PV

updateStrategy:
  type: RollingUpdate


## Specifies whether a ServiceAccount should be created
##
serviceAccount:
  create: false
  ## The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the fullname template
  ##
  name: ""

image:
  repository: openg2p/openg2p-pbms-bg-task-celery-beat-producers
  tag: "3.0.0"
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always
  ## Optionally specify an array of imagePullSecrets.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets:
  #   - myRegistryKeySecretName

## Deployment pod host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []

## Affinity for pod assignment. Evaluated as a template.
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## Pod affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAffinityPreset: ""

## Pod anti-affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
## Allowed values: soft, hard
##
podAntiAffinityPreset: soft

## Node affinity preset
## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
## Allowed values: soft, hard
##
nodeAffinityPreset:
  ## Node affinity type
  ## Allowed values: soft, hard
  ##
  type: ""
  ## Node label key to match
  ## E.g.
  ## key: "kubernetes.io/e2e-az-name"
  ##
  key: ""
  ## Node label values to match
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []

## Node labels for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}

## Tolerations for pod assignment. Evaluated as a template.
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []

##  pods' priority.
## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
##
# priorityClassName: ""

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
##
podSecurityContext:
  enabled: false
  fsGroup: 1001

## Add init containers to the  pods.
## Example:
## initContainers:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
initContainers: []

## lifecycleHooks for the  container to automate configuration before or after startup.
##
lifecycleHooks: {}

## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
## Clamav container already runs as 'mosip' user, so we may not need to enable this
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true

envVars:
  BG_TASK_CELERY_BEAT_PRODUCER_FREQUENCY: 10
  BG_TASK_CELERY_BEAT_BATCH_SIZE: 500
  BG_TASK_CELERY_BEAT_NO_OF_TASKS_TO_PROCESS: 2

  # Background Task Database
  BG_TASK_CELERY_BEAT_DB_HOSTNAME: '{{ tpl .Values.global.postgresqlHost $ }}'
  BG_TASK_CELERY_BEAT_DB_PORT: 5432
  BG_TASK_CELERY_BEAT_DB_DBNAME: '{{ tpl .Values.global.pbmsBgTaskDB $ }}'
  BG_TASK_CELERY_BEAT_DB_USERNAME: '{{ tpl .Values.global.pbmsBgTaskDBUser $ }}'

  # Social Registry Database
  BG_TASK_CELERY_BEAT_DB_HOSTNAME_SR: '{{ tpl .Values.global.postgresqlHost $ }}'
  BG_TASK_CELERY_BEAT_DB_PORT_SR: 5432
  BG_TASK_CELERY_BEAT_DB_DBNAME_SR: '{{ tpl .Values.global.registryDB $ }}'
  BG_TASK_CELERY_BEAT_DB_USERNAME_SR: '{{ tpl .Values.global.registryDBUser $ }}'

  # PBMS Database
  BG_TASK_CELERY_BEAT_DB_HOSTNAME_PBMS: '{{ tpl .Values.global.postgresqlHost $ }}'
  BG_TASK_CELERY_BEAT_DB_PORT_PBMS: 5432
  BG_TASK_CELERY_BEAT_DB_DBNAME_PBMS: '{{ tpl .Values.global.pbmsDB $ }}'
  BG_TASK_CELERY_BEAT_DB_USERNAME_PBMS: '{{ tpl .Values.global.pbmsDBUser $ }}'

  BG_TASK_CELERY_BEAT_CELERY_BROKER_URL: redis://{{ tpl .Values.global.redisInstallationName $ }}:6379/0
  BG_TASK_CELERY_BEAT_CELERY_BACKEND_URL: redis://{{ tpl .Values.global.redisInstallationName $ }}:6379/0

envVarsFrom:
  BG_TASK_CELERY_BEAT_DB_PASSWORD:
    secretKeyRef:
      name: '{{ tpl .Values.global.pbmsBgTaskDBSecret $ }}' 
      key: '{{ tpl .Values.global.pbmsBgTaskDBUserPasswordKey $ }}' 
  BG_TASK_CELERY_BEAT_DB_PASSWORD_SR:
    secretKeyRef:
      name: '{{ tpl .Values.global.registryDBSecret $ }}'
      key: '{{ tpl .Values.global.registryDBUserPasswordKey $ }}'
  BG_TASK_CELERY_BEAT_DB_PASSWORD_PBMS :
    secretKeyRef:
      name: '{{ tpl .Values.global.pbmsDBSecret $ }}'
      #key: '{{ tpl .Values.global.pbmsDBuserPasswordKey $ }}'
      key: '{{ .Values.global.pbmsDBuserPasswordKey }}'

## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
## We usually recommend not to specify default resources and to leave this as a conscious
## choice for the user. This also increases chances charts run on environments with little
## resources, such as Minikube. If you do want to specify resources, uncomment the following
## lines, adjust them as necessary.
# resources:
#   limits:
#     cpu: 1000m
#     memory: 500Mi
#   requests:
#     cpu: 200m
#     memory: 200Mi
resources: {}

## Configure extra options for liveness and readiness probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes
##
startupProbe:
  enabled: false
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 30
  successThreshold: 1

livenessProbe:
  enabled: false
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 20
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  enabled: false
  httpGet:
    path: /ping
    port: http
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

## Add sidecars to the  pods.
## Example:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: []

postgresCheckerInit:
  enabled: true
  image:
    repository: jbergknoff/postgresql-client
    tag: latest
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - myRegistryKeySecretName
  command:
  - 'sh'
  - '-c'
  - >-
    until pg_isready
    -U ${BG_TASK_CELERY_BEAT_DB_USERNAME}
    -h ${BG_TASK_CELERY_BEAT_DB_HOSTNAME}
    -p ${BG_TASK_CELERY_BEAT_DB_PORT:-5432}
    -d ${BG_TASK_CELERY_BEAT_DB_DBNAME:-bgtaskdb};
    do sleep 3;
    done

